name: 'wait-for-github-status-action'
description: 'description'
author: 'Sibz@EntityZero'
branding:
  icon: 'clock'  
  color: 'yellow'
inputs:
  name:
    description: 'input'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
