name: 'wait-for-github-status-action'
description: 'description'
author: 'Sibz@EntityZero'
branding:
  icon: 'clock'  
  color: 'yellow'
inputs:
  authToken:
    description: 'authToken'
    required: true
  contexts:
    description: 'semi-colon separated list of contexts (check names)'
    required: true
  timeout:
    description: 'max time to wait'
    required: false
  notPresentTimeout:
    description: 'max time to wait for a check to become present'
    required: false
  pollInterval:
    description: 'time to wait inbetween polling for states'
    required: false
  completeStates:
    description: "semi-colon separated list of states to consider complete, default: 'success'"
    required: false
  failureStates:
    description: "semi-colon separated list of states to consider failure, default 'error;failure'"
    required: false
  ref:
    description: 'ref'
    required: false
    default: ${{ github.sha }}
  owner:
    description: 'GitHub username of repository owner'
    required: false
    default: ${{ github.repository_owner }}
  repository: 
    description: 'GitHub repository where sha exist'
    required: false
    default: ${{ github.repository }}
outputs:
  result:
    description: "'success', 'failure' or 'timeout'"
  numberOfFailedChecks:
    description: 'number of failing checks'
  failedCheckNames:
    description: "semi-colon separated list of failed checks"
  failedCheckStates:
    description: "semi-colon separated list of check results, on timeout will be state or 'not_present'"
runs:
  using: 'node12'
  main: 'dist/index.js'
