name: 'test'
on: 
  pull_request:
  push:
    branches:
      - master

jobs:        
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run
      id: stepId
      uses: ./
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        contexts: 'Test State'
        timeout: 120
        notPresentTimeout: 60
    - name: result
      run: 'echo ${{ steps.stepId.outputs.result }} ${{ steps.stepId.outputs.failedCheckNames }}'

  setup_state:
    runs-on: ubuntu-latest
    steps:
    - uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        status: 'success'
        context: 'Test State'
    
      
    